"""Sample module generated by the Coding Agent."""

def greet(name: str) -> str:
    """Return a friendly greeting."""
    return f"Greetings, {name}! (v2) Built by the multi-agent system."


if __name__ == "__main__":
    print(greet("World"))
